Meeting/urls.py
from django.contrib import admin
from django.urls import path, include
from onlinemeet.views import user_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meeting/', include('onlinemeet.urls', namespace='online-meet')),
    path('login/', user_login, name='login'),

]

onlinemeet/urls.py
from django.urls import path
from . import views

app_name = 'online-meet'

urlpatterns = [
    path('', views.home, name='home'),
    path('join/', views.join_meeting, name='join-meet'),
    path('my-meetings/', views.meeting_list, name='meeting_list'),
    path('live-meeting/<unique_meeting_name>/', views.meeting, name='meeting'),

]

onlinemeet/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.utils.text import slugify
from datetime import timedelta
from django.utils import timezone

class Meeting(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)  # creator of the meeting
    title_of_meeting = models.CharField(max_length=150)
    created = models.DateTimeField(auto_now_add=True)  # the time meeting was created
    updated = models.DateTimeField(auto_now=True)  # time meeting was updated
    duration = models.PositiveIntegerField(null=True, blank=True)
    starting_date_time = models.DateTimeField()
    ending_date_time = models.DateTimeField(null=True, blank=True)
    unique_meeting_name = models.TextField(blank=True, null=True)

    def __str__(self):
        return '%s: %s' % (self.creator, self.title_of_meeting)

    # def save(self, *args, **kwargs):
    #     if self.duration:
    #         self.ending_date_time = self.starting_date_time + timedelta(minutes=self.duration)

    #     if not self.unique_meeting_name:
    #         self.unique_meeting_name = slugify(
    #             str(self.title_of_meeting) + '-' + str(uuid.uuid4().hex[:6].upper())
    #         )
    #     return super(Meeting, self).save()

    @property
    def meeting_time(self):
        """
        this is a model property for checking if it is meeting time. we shall be using
        this in the views
        """
        return (timezone.now() >= self.starting_date_time)


    # @property
    # def after_meeting(self):
    #     """
    #     will check if the time for the meeting has passed, i.e. meeting has ended"""

    #     return (timezone.now() >= self.ending_date_time)

    

onlinemeet/forms.py
from django import forms
from .models import Meeting


class DateTimePickerInput(forms.DateTimeInput):
    input_type= 'datetime-local'
    input_formats=['%m/%d/%y %H:%M %p']

class MeetingCreateForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ["title_of_meeting", "starting_date_time"]

        widgets = {
            'starting_date_time': DateTimePickerInput(),
        }

class MeetingJoinForm(forms.Form):
    unique_meeting_name = forms.CharField(max_length=20)

    class Meta:
        fields = ['unique_meeting_name']

onlinemeet/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect, HttpResponse
from .forms import MeetingCreateForm, MeetingJoinForm
from .models import Meeting
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.urls import reverse
from django.contrib import messages
from datetime import datetime, timezone as tz
from django.utils import timezone
import uuid
from django.utils.text import slugify

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        if username and password:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request,user)
                return redirect('online-meet:home')
    else:
        return render(request, 'login.html')
    return render(request, 'login.html')  

@login_required
def home(request):
    form = MeetingCreateForm()
    if request.method == 'POST':
        form = MeetingCreateForm(request.POST)
        if form.is_valid():
            fm = form.save(commit=False)
            # since in our form, we do not want to be selecting users,
            # we have to set the creator as the current user.
            fm.creator = request.user
            fm.unique_meeting_name = slugify(
                str(form.cleaned_data['title_of_meeting']) + '-' + str(uuid.uuid4().hex[:6].upper())
            )
            fm.save()
            unique_meeting_name = fm.unique_meeting_name
            return HttpResponseRedirect(reverse('online-meet:meeting',kwargs={'unique_meeting_name': unique_meeting_name}))
    return render(request, 'onlinemeet/home.html', {'form': form})


@login_required()  # to ensure only logged in user can view this page.
def meeting_list(request):
    """We are going to filter the meeting, so only the registered user can view
    the page, and then all meeting created by such individual will be displayed"""
    user = request.user
    # meeting_url = request.build_absolute_uri()
    meetings = Meeting.objects.filter(creator=user)

    return render(request, 'onlinemeet/meeting_list.html', {'meetings': meetings})

@login_required
def join_meeting(request):
    form = MeetingJoinForm()
    if request.method == 'POST':
        form = MeetingJoinForm(request.POST)
        if form.is_valid():
            unique_meeting_name = form.cleaned_data['unique_meeting_name']
            if Meeting.objects.filter(unique_meeting_name=unique_meeting_name).exists():
                return HttpResponseRedirect(reverse('online-meet:meeting', kwargs={'unique_meeting_name':unique_meeting_name}))
            return HttpResponse(f'Meeting name {unique_meeting_name} doesnot exits')
    return render(request, 'onlinemeet/join_meeting.html', {'form': form})

@login_required
def meeting(request, unique_meeting_name):
    message = None
    if not unique_meeting_name:
        return HttpResponse(f"No any meeting is running with the meeting code: {unique_meeting_name}")
    try:
        meeting = Meeting.objects.get(unique_meeting_name=unique_meeting_name)
    except:
        return HttpResponse(f"No any meeting is running with the meeting code: {unique_meeting_name}")

    if not meeting.meeting_time:
        """
        will check if it is not time for the meeting using the property we declared in the model.
        """
        now = timezone.localtime()
        t = abs(now - meeting.starting_date_time).total_seconds()
        MinutesGet, SecondsGet = divmod(t, 60)
        HoursGet, MinutesGet = divmod(MinutesGet, 60)

        message = f"it is not the time for meeting {meeting.title_of_meeting}, Meeting starts in {HoursGet} Hours : {MinutesGet} Minutes : {'{:.2f}'.format(SecondsGet)} Seconds."
        # return render(request, 'onlinemeet/meeting_list.html', {'meetings': meetings})
        print(now, message)

        messages.warning(request, message)
        # return render(request, 'onlinemeet/meeting_list.html', {'meetings': meetings})
        return HttpResponseRedirect(reverse('online-meet:home'))
    
    # elif meeting.after_meeting:
    #     """ will check if the meeting time has passed"""
    #     now = timezone.localtime()
    #     t = abs(meeting.ending_date_time - now).total_seconds()
    #     MinutesGet, SecondsGet = divmod(t, 60)
    #     HoursGet, MinutesGet = divmod(MinutesGet, 60)

    #     message = f"The meeting {meeting.title_of_meeting}, ended {HoursGet} Hours : {MinutesGet} Minutes : {'{:.2f}'.format(SecondsGet)} Seconds."
    #     print(now, message)
    #     messages.warning(request, message)
    #     return HttpResponseRedirect(reverse('online-meet:home'))


    if request.user != meeting.creator:
        """check to know if the current user is the creator of the meeting
        if True, then the person will be redirected to a page that has moderator privileges, else, redirect the guest to the guest page."""
        return render(request, 'onlinemeet/guest.html', {'meeting': meeting,
        "message": message})

    return render(request, 'onlinemeet/meeting_page.html', {'meeting': meeting})

onlinemeet/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Login Page</h2>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="username">
        <input type="password" name="password">
        <button type="submit">Login</button>
      </form>
</body>
</html>

onlinemeet/templates/onlinemeet/guest.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LIVE MEETING PAGE</title>
</head>
<body>
<h2>Title: {{meeting.title_of_meeting}}</h2>
                <div id="meet">

                </div>
{% block script %}
<script src='https://meet.jit.si/external_api.js'></script>
<script>
    const domain = 'meet.jit.si'
    const options = {
        roomName: '{{meeting.unique_meeting_name}}',
        width: 1000,
        height: 800,
        parentNode: document.querySelector('#meet'),
        lang: 'en',  // default language, change the language to english
        configOverwrite: {
            disableRemoteMute: true,  //DISABLE MUTE ALL FEATURE IN JITSI
            remoteVideoMenu: {
                // If set to true the 'Kick out' button will be disabled for the guest.
                disableKick: true
            },
        },
        interfaceConfigOverwrite: {
            filmStripOnly: true,
            /* the toolbars that will be visible for the guest of the meeting.*/
            TOOLBAR_BUTTONS: ['microphone', 'camera', 'closedcaptions', 'desktop', 
            'fullscreen', 'fodeviceselection', 'chat', 'etherpad', 'raisehand', 'filmstrip', 'shortcuts', 'tileview','download', 'help','hangup'], 
        }
    };
const api = new JitsiMeetExternalAPI(domain, options);
</script>

{% endblock %}
</body>

</html>

onlinemeet/templates/onlinemeet/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meeting Creation Page</title>
</head>

<body>
    <form method="post">
        {%csrf_token%}
        <h2>Hello world, I am Home</h2>
        {{form.as_p}}
        <input type="submit" value="Create Meeting">
        <button><a href="{% url 'online-meet:join-meet' %}">join</a></button>
    </form>
</body>

</html>

onlinemeet/templates/onlinemeet/join_meeting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Join Meeting">
    </form>
</body>
</html>

onlinemeet/templates/onlinemeet/meetin_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Meetings.</title>
</head>
<body>
    <h3>All Meetings created by: {{request.user | upper}}</h3>
    {% if message %}
        {{message}}
    {% endif %}

<table>
    <thead>
    <tr>
        <th>Creator</th>
        <th>Title</th>
        <th>Starting date time</th>
        <th>Ending Date & Time</th>
        <th>Join</th>
    </tr>
    </thead>
    {% for meeting in meetings %}
    <tbody>


    <tr>
    <td>{{meeting.creator}}</td>
    <td>{{meeting.title_of_meeting}}</td>
    <td>{{meeting.starting_date_time}}</td>
    <td>{{meeting.ending_date_time}}</td>
    <td><a href="{% url 'meeting' meeting.unique_meeting_name %}">Join Meeting</a>
        <td><input type="hidden" name="meeting_{{forloop.counter}}" id="{{meeting.id}}" value="{{ request.scheme }}://{{ request.get_host }}{% url 'meeting' meeting.unique_meeting_name %}" id="meeting_link"> 
            <button onclick="myFunction('{{meeting.id}}')">Copy Link</button></td>
    </tr>
    </tbody>
    {% endfor %}

</table>

    <script>
        function myFunction(mid) {
            console.log(mid);
            //var myButtons = document.querySelectorAll('.myclass');
            var copyText = document.getElementById(mid);
            console.log(copyText);
            //copyText.select();
            //copyText.setSelectionRange(0, 99999);

            navigator.clipboard.writeText(copyText.value);
        alert("Meeting Link copied successfully to clipboard. ");
        }
    </script>
</body>
</html>

onlinemeet/templates/onlinemeet/meeting_page.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LIVE MEETING PAGE</title>
</head>
<body>
<h2>Title: {{meeting.title_of_meeting}}</h2>
                <div id="meet">

                </div>
{% block script %}
<script src='https://meet.jit.si/external_api.js'></script>
<script>
    const domain = 'meet.jit.si';
    const options = {
        roomName: '{{meeting.unique_meeting_name}}',
        width: 1000,
        height: 600,
        parentNode: document.querySelector('#meet'),
        lang: 'en',  // default language, change the language to english
        configOverwrite: {
            startWithAudioMuted: true, // mute device audio by default
            startWithVideoMuted: true, // mute video by default
            prejoinPageEnabled: true, // enable prejoin page to set name
            enableLobbyChat: true,  // enable lobby chat
            localRecording: true,
            startWithAudioMuted: true,
            disableInitialGUM: true,

        },
        interfaceConfigOverwrite: {
            SHOW_CHROME_EXTENSION_BANNER: false, //ok
            TOOLBAR_ALWAYS_VISIBLE: true, // ok
            SETTINGS_SECTIONS: ['devices', 'language'],
            SHOW_POWERED_BY: false,
            TOOLBAR_ALWAYS_VISIBLE: true,
        },
        /* The toolbars that will be available for only the creator of the meeting */
        TOOLBAR_BUTTONS: ["microphone","camera","desktop","hangup","chat","raisehand","participants-pane","tileview","toggle-camera","invite","videoquality","livestreaming","mute-everyone","mute-video-everyone","sharedvideo","shareaudio","select-background","stats","settings","filmstrip"],
    };
const api = new JitsiMeetExternalAPI(domain, options);
</script>

{% endblock %}
</body>

</html>